<a href="https://colab.research.google.com/github/Garden1107/Cpp-Self-study/blob/main/%EC%9B%8C%ED%81%AC%EC%8B%9C%ED%8A%B81%EC%B0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

문제1. 국적별 유학연수 기타 자료 파일을 활용하여, 국적1과 기타 열을 삭제한 데이터만 나올 수 있게 전체코드를 작성하시오.
- 최종 결과가 들어갈 변수 이름은 ‘s1’으로 지정
- 코드를 작성하고, 코드 실행 결과도 캡처하시오

In [ ]:
import pandas as pd
a = pd.read_csv('국적별 유학연수 기타 자료.csv', encoding='cp949')

In [ ]:
a

     국적1        국적    유학연수      기타
0   아시아주        중국  22,250  13,454
1   아시아주        일본   2,702   1,318
2   아시아주        대만     910     372
3   아시아주        홍콩     422     231
4   아시아주       마카오      24       7
5   아시아주       필리핀     206   5,985
6   아시아주     인도네시아     901   4,305
7   아시아주        태국     361   3,377
8   아시아주       베트남  11,159  10,775
9   아시아주        인도     428   1,813
10  아시아주     말레이시아     464   1,510
11  아시아주      싱가포르     224   1,186
12  아시아주        몽골     975     455
13  아시아주    우즈베키스탄   1,491   2,496
14  아시아주       미얀마     348   2,208
15  아시아주       GCC      98     171
16  아시아주     카자흐스탄     372   1,055
17  아시아주      튀르키예     147     925
18  아시아주      캄보디아     110   2,157
19  아시아주      스리랑카      76   1,429
20  아시아주     방글라데시     297     983
21  아시아주      파키스탄     281     503
22  아시아주      이스라엘      14      35
23  아시아주        이란      38      30
24  아시아주    아시아 기타     906   4,125
25    미주        미국   1,610  13,017
26    미주       캐나다     153   2,817
27    미주       브라질     115     232
28    미주       멕시코     183     189
29    미주     미주 기타     254     223
30   대양주   오스트레일리아      90   1,102
31   대양주      뉴질랜드      19     578
32   대양주    대양주 기타       3       9
33  아프리카  남아프리카공화국      14     703
34  아프리카   아프리카 기타     481   1,006

In [ ]:
a.drop(columns=['국적1' , '기타'] , axis=1)

          국적    유학연수
0         중국  22,250
1         일본   2,702
2         대만     910
3         홍콩     422
4        마카오      24
5        필리핀     206
6      인도네시아     901
7         태국     361
8        베트남  11,159
9         인도     428
10     말레이시아     464
11      싱가포르     224
12        몽골     975
13    우즈베키스탄   1,491
14       미얀마     348
15       GCC      98
16     카자흐스탄     372
17      튀르키예     147
18      캄보디아     110
19      스리랑카      76
20     방글라데시     297
21      파키스탄     281
22      이스라엘      14
23        이란      38
24    아시아 기타     906
25        미국   1,610
26       캐나다     153
27       브라질     115
28       멕시코     183
29     미주 기타     254
30   오스트레일리아      90
31      뉴질랜드      19
32    대양주 기타       3
33  남아프리카공화국      14
34   아프리카 기타     481

In [ ]:
s1=a.drop(columns=['국적1' , '기타'] , axis=1)

In [ ]:
s1

          국적    유학연수
0         중국  22,250
1         일본   2,702
2         대만     910
3         홍콩     422
4        마카오      24
5        필리핀     206
6      인도네시아     901
7         태국     361
8        베트남  11,159
9         인도     428
10     말레이시아     464
11      싱가포르     224
12        몽골     975
13    우즈베키스탄   1,491
14       미얀마     348
15       GCC      98
16     카자흐스탄     372
17      튀르키예     147
18      캄보디아     110
19      스리랑카      76
20     방글라데시     297
21      파키스탄     281
22      이스라엘      14
23        이란      38
24    아시아 기타     906
25        미국   1,610
26       캐나다     153
27       브라질     115
28       멕시코     183
29     미주 기타     254
30   오스트레일리아      90
31      뉴질랜드      19
32    대양주 기타       3
33  남아프리카공화국      14
34   아프리카 기타     481

문제2. 국적별 관광 상용 자료 파일을 활용하여, 상용목적으로 가장 많이 방문한 국가순으로 정렬하는 전체코드를 작성하시오.
- 상용목적이 500건 이상인 데이터만 표시할 것
- 상용목적이 많은 순서대로 표시할 것 (내림차순으로 표시하는 코드 작성)
- 최종 결과가 들어갈 변수 이름은 ‘s2’로 지정

In [ ]:
import pandas as pd
a = pd.read_excel('국적별 관광 상용 자료.xlsx')

In [ ]:
a

   국적별(1)    국적별(2)     관광    상용
0    아시아주        중국   8813  1340
1    아시아주        일본  89217  1084
2    아시아주        대만  46456   224
3    아시아주        홍콩  15534    49
4    아시아주       마카오    312     3
5    아시아주       필리핀   7880   229
6    아시아주     인도네시아   8754    87
7    아시아주        태국  24152    61
8    아시아주       베트남   6377   456
9    아시아주        인도   1217  1188
10   아시아주     말레이시아  14448    55
11   아시아주      싱가포르  10484   273
12   아시아주        몽골   8365    41
13   아시아주    우즈베키스탄    491   166
14   아시아주       미얀마    668    38
15   아시아주       GCC    970    28
16   아시아주     카자흐스탄   1340    12
17   아시아주      튀르키예    514    13
18   아시아주      캄보디아    680     6
19   아시아주      스리랑카    104    22
20   아시아주     방글라데시     89    51
21   아시아주      파키스탄    126    91
22   아시아주      이스라엘    343     5
23   아시아주        이란     30    33
24   아시아주    아시아 기타   1119   654
25     미주        미국  29488   153
26     미주       캐나다   6009    33
27     미주       브라질    651    27
28     미주       멕시코    472     4
29     미주     미주 기타   1169    16
30    대양주   오스트레일리아   6585    95
31    대양주      뉴질랜드   1041    24
32    대양주    대양주 기타     39     1
33   아프리카  남아프리카공화국    210     3
34   아프리카   아프리카 기타    472   298

In [ ]:
a.query('상용>=500')
b=a.query('상용>=500')

In [ ]:
b.sort_values('상용', ascending=False)

   국적별(1)  국적별(2)     관광    상용
0    아시아주      중국   8813  1340
9    아시아주      인도   1217  1188
1    아시아주      일본  89217  1084
24   아시아주  아시아 기타   1119   654

In [ ]:
s2=b.sort_values('상용', ascending=False)

In [ ]:
s2

   국적별(1)  국적별(2)     관광    상용
0    아시아주      중국   8813  1340
9    아시아주      인도   1217  1188
1    아시아주      일본  89217  1084
24   아시아주  아시아 기타   1119   654